baseURL = "https://blog.adamekka.com/"
languageCode = "en-us"
title = "Adamekka's Blog"

[params]
showLanguageSelector = false
fullWidthTheme = true
centerTheme = true
autoCover = true
showLastUpdated = false
readingTime = true
Toc = false
# TocTitle = "Table of Contents"
dateFormat = "2.1.2006 3:04 PM GMT-07"
accentColor = "green"


[languages]
[languages.en]
languageName = "English"
title = "Adamekka's Blog"

[languages.en.params]
subtitle = ""
owner = "Adamekka"
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[languages.en.params.logo]
logoText = "Adamekka's Blog"
logoHomeLink = "/"

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[module]
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v4'
